import {
  dellImage1,
  dellImage2,
  headSetImage1,
  headSetImage2,
  iPhoneImage1,
  iPhoneImage2,
  iPhoneImage3,
  macBookImage1,
  macBookImage2,
  macBookImage3,
  nintendoSwitchImage1,
  nintendoSwitchImage2,
  ps5Image1,
  ps5Image2,
  ps5Image3,
  samsungImage1,
  samsungImage2,
} from "../../assets";
import { Product } from "../../types/global";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Macbook Pro (2024)",
    slug: "macbook-pro-2024",
    heroImage: macBookImage1,
    image: [macBookImage1, macBookImage2, macBookImage3],
    price: 899.99,
    category: {
      image: macBookImage1,
      name: "Laptops",
      slug: "laptops",
    },
    quantity: 5,
  },
  {
    id: 5,
    title: "Dell XPS 13",
    slug: "dell-xps-13",
    heroImage: dellImage1,
    image: [dellImage1, dellImage2],
    price: 1099.99,
    category: {
      image: macBookImage1,
      name: "Laptops",
      slug: "laptops",
    },
    quantity: 7,
  },
  {
    id: 2,
    title: "IPhone 15",
    slug: "i-phone-15",
    heroImage: iPhoneImage1,
    image: [iPhoneImage2, iPhoneImage3],
    price: 999.99,
    category: {
      image: iPhoneImage1,
      name: "Phones",
      slug: "phones",
    },
    quantity: 10,
  },
  {
    id: 6,
    title: "Samsung Galaxy S21",
    slug: "samsung-galaxy-s21",
    heroImage: samsungImage1,
    image: [samsungImage1, samsungImage2],
    price: 799.99,
    category: {
      image: iPhoneImage1,
      name: "Phones",
      slug: "phones",
    },
    quantity: 12,
  },
  {
    id: 3,
    title: "Headset",
    slug: "headset",
    heroImage: headSetImage1,
    image: [headSetImage1, headSetImage2],
    price: 499.99,
    category: {
      image: headSetImage1,
      name: "Accessories",
      slug: "accessories",
    },
    quantity: 15,
  },
  {
    id: 4,
    title: "PlayStation 5",
    slug: "playstation-5",
    heroImage: ps5Image1,
    image: [ps5Image1, ps5Image2, ps5Image3],
    price: 699.99,
    category: {
      image: ps5Image1,
      name: "Gaming",
      slug: "gaming",
    },
    quantity: 3,
  },
  {
    id: 7,
    title: "Nintendo Switch",
    slug: "nintendo-switch",
    heroImage: nintendoSwitchImage1,
    image: [nintendoSwitchImage1, nintendoSwitchImage2],
    price: 299.99,
    category: {
      image: ps5Image1,
      name: "Gaming",
      slug: "gaming",
    },
    quantity: 8,
  },
];
